#!/bin/bash
# This script forks a Manjaro repo to a Kamarada (GitHub) repo

# Example:
# fork-manjaro https://gitlab.manjaro.org/plymouth-themes/plymouth-manjaro.git plymouth-kamarada

# Create an empty GitHub repo before running this script:
# https://github.com/organizations/kamarada/repositories/new

REPOS_DIR="/home/vinicius/dev/projects/git/kamarada"
REPOS_CONFIG="$REPOS_DIR/scripts/repos-config.json"

REMOTE_UPSTREAM=$1
REPO_NAME=$2
REMOTE_FORK="git@github.com:kamarada/$REPO_NAME.git"

git clone "$REMOTE_UPSTREAM" "$REPO_NAME"
cd "$REPO_NAME"

git remote rename origin manjaro
git remote add origin "$REMOTE_FORK"

git branch -m stable
git branch --unset-upstream
git push origin -u stable
# Let's create the stable branch first so it becomes the default branch

git checkout -b manjaro
git push origin -u manjaro

git checkout -b testing
git push origin -u testing

git fetch manjaro

# Add to repos-config.json

NEW_REPO_CONFIG=$(cat <<EOF
{
    "folder": "$REPO_NAME",
    "manjaro": "$REMOTE_UPSTREAM",
    "kamarada": "$REMOTE_FORK"
}
EOF
)

TMP_FILE=$(mktemp)

jq --argjson obj "$NEW_REPO_CONFIG" '
  . + [$obj] | sort_by(.folder)
' "$REPOS_CONFIG" > "$TMP_FILE"

mv "$TMP_FILE" "$REPOS_CONFIG"
