#!/bin/bash
# This script forks an Arch Linux repo to a Kamarada (GitHub) repo

# Example:
# fork-archlinux https://gitlab.archlinux.org/archlinux/packaging/packages/papirus-icon-theme.git papirus-icon-theme-kamarada

# Create an empty GitHub repo before running this script:
# https://github.com/organizations/kamarada/repositories/new

REPOS_DIR="/home/vinicius/dev/projects/git/kamarada"
REPOS_CONFIG="$REPOS_DIR/scripts/repos-config.json"

UPSTREAM_REMOTE_URL=$1
REPO_NAME=$2
KAMARADA_REMOTE_URL="git@github.com:kamarada/$REPO_NAME.git"

git clone "$UPSTREAM_REMOTE_URL" "$REPO_NAME"
cd "$REPO_NAME"

git remote rename origin archlinux
git remote add origin "$KAMARADA_REMOTE_URL"

git branch -m stable
git branch --unset-upstream
git push origin -u stable
# Let's create the stable branch first so it becomes the default branch

git checkout -b archlinux
git push origin -u archlinux

git checkout -b testing
git push origin -u testing

git fetch archlinux

# Add to repos-config.json

NEW_REPO_CONFIG=$(cat <<EOF
{
    "folder": "$REPO_NAME",
    "upstream": "archlinux",
    "upstream_url": "$UPSTREAM_REMOTE_URL",
    "kamarada_url": "$KAMARADA_REMOTE_URL"
}
EOF
)

TMP_FILE=$(mktemp)

jq --argjson obj "$NEW_REPO_CONFIG" '
  . + [$obj] | sort_by(.folder)
' "$REPOS_CONFIG" > "$TMP_FILE"

mv "$TMP_FILE" "$REPOS_CONFIG"
