#!/bin/bash
# This script replicates the Linux Kamarada repository structure

#REPOS_DIR="/home/vinicius/dev/projects/git/kamarada"
REPOS_DIR="/home/vinicius/dev/projects/git/teste"
#REPOS_CONFIG="$REPOS_DIR/scripts/repos-config.json"
REPOS_CONFIG="/home/vinicius/dev/projects/git/kamarada/scripts/repos-config.json"
KAMARADA_BRANCH="testing"

# Define color variables (using \033 for maximum portability)
GREEN='\033[32m'
RESET='\033[0m'

call_jq() {
    jq -r "$@" $REPOS_CONFIG
}

cd "$REPOS_DIR"

NUMBER_OF_REPOS=$(call_jq '. | length')

for ((r = 0; r < NUMBER_OF_REPOS; r++ ))
do
    REPO_NAME=$(call_jq -r ".[$r].folder")
    if [ -d "$REPOS_DIR/$REPO_NAME" ]; then
        printf "${GREEN}$REPO_NAME: directory exists, skipping...${RESET}\n"
    else
        printf "${GREEN}$REPO_NAME: directory does not exist, fetching...${RESET}\n"
        KAMARADA_REMOTE_URL=$(call_jq -r ".[$r].kamarada_url")
        git clone "$KAMARADA_REMOTE_URL" "$REPO_NAME"
        cd "$REPO_NAME"
        git checkout "$KAMARADA_BRANCH"

        # Set up upstream remote
        UPSTREAM=$(call_jq -r ".[$r].upstream")
        UPSTREAM_REMOTE_URL=$(call_jq -r ".[$r].upstream_url")
        git remote add "$UPSTREAM" "$UPSTREAM_REMOTE_URL"
        git fetch "$UPSTREAM"
        printf "${GREEN}$REPO_NAME: set up with $UPSTREAM remote $UPSTREAM_REMOTE_URL${RESET}\n"

        cd ..
    fi
done