#!/bin/bash
# This script replicates the Linux Kamarada repository structure

REPOS_DIR="/home/vinicius/dev/projects/git/kamarada"
REPOS_CONFIG="$REPOS_DIR/scripts/repos-config.json"
CHECKOUT_BRANCH="testing"

# Define color variables (using \033 for maximum portability)
GREEN='\033[32m'
RESET='\033[0m'

call_jq() {
    jq -r "$@" $REPOS_CONFIG
}

cd "$REPOS_DIR"

NUMBER_OF_REPOS=$(call_jq '. | length')

for ((r = 0; r < NUMBER_OF_REPOS; r++ ))
do
    REPO_NAME=$(call_jq -r ".[$r].folder")
    if [ -d "$REPOS_DIR/$REPO_NAME" ]; then
        printf "${GREEN}$REPO_NAME: directory exists, skipping...${RESET}\n"
    else
        printf "${GREEN}$REPO_NAME: directory does not exist, fetching...${RESET}\n"
        KAMARADA_REMOTE=$(call_jq -r ".[$r].kamarada")
        git clone "$KAMARADA_REMOTE" "$REPO_NAME"
        cd "$REPO_NAME"
        git checkout "$CHECKOUT_BRANCH"

        # Set up upstream remote
        MANJARO_REMOTE=$(call_jq -r ".[$r].manjaro")
        AUR_REMOTE=$(call_jq -r ".[$r].aur")
        if [[ "$MANJARO_REMOTE" != "null" ]]; then
            git remote add manjaro "$MANJARO_REMOTE"
            git fetch manjaro
            printf "${GREEN}$REPO_NAME: set up with Manjaro remote $MANJARO_REMOTE${RESET}\n"
        elif [[ "$AUR_REMOTE" != "null" ]]; then
            git remote add aur "$AUR_REMOTE"
            git fetch aur
            printf "${GREEN}$REPO_NAME: set up with AUR remote $AUR_REMOTE${RESET}\n"
        fi

        cd ..
    fi
done