#!/bin/bash

LOCAL_FOLDER="/home/vinicius/dev/projects/sf/kamarada/manjaro/"
PKGS_FILE=$(find "$LOCAL_FOLDER" -name "*.pkgs")

# List installed packages
#INSTALLED_PACKAGES=$(pacman -Qr /)

read -r -d '' PACKAGES_OF_INTEREST << EOF
linux-meta
linux616
xorg-server
wayland
gnome-shell
libreoffice-still
firefox
chromium
vlc
evolution
brasero
cups
drawing
firewalld
gparted
hplip
jdk21-openjdk
keepassxc
linphone-desktop
pdfsam
pidgin
python
samba
tor
transmission-gtk
vim
wine
calamares-kamarada
flatpak
EOF

# For each installed package
for PACKAGE in $PACKAGES_OF_INTEREST
do
    grep "^$PACKAGE " "$PKGS_FILE"
done
